export enum CallErrorCode {
  CALL_NOT_FOUND = 'CALL_NOT_FOUND',
  CALL_CREATION_FAILED = 'CALL_CREATION_FAILED',
  CALL_UPDATE_FAILED = 'CALL_UPDATE_FAILED',
  CALL_DELETE_FAILED = 'CALL_DELETE_FAILED',
  INVALID_CALL_STATUS = 'INVALID_CALL_STATUS',
  CALL_ALREADY_COMPLETED = 'CALL_ALREADY_COMPLETED',
  CALL_ALREADY_CANCELLED = 'CALL_ALREADY_CANCELLED',
  NO_AMBULANCE_ASSIGNED = 'NO_AMBULANCE_ASSIGNED',
  AMBULANCE_DISPATCH_FAILED = 'AMBULANCE_DISPATCH_FAILED',
  HOSPITAL_NOT_SELECTED = 'HOSPITAL_NOT_SELECTED',
  HOSPITAL_SELECTION_FAILED = 'HOSPITAL_SELECTION_FAILED',
  INVALID_LOCATION = 'INVALID_LOCATION',
  ROUTE_CALCULATION_FAILED = 'ROUTE_CALCULATION_FAILED',
  NO_HOSPITALS_FOUND = 'NO_HOSPITALS_FOUND',
  CONTACT_NOTIFICATION_FAILED = 'CONTACT_NOTIFICATION_FAILED',
  DRIVER_RESPONSE_FAILED = 'DRIVER_RESPONSE_FAILED',
  NO_AVAILABLE_DRIVERS = 'NO_AVAILABLE_DRIVERS',
  INVALID_USER = 'INVALID_USER',
  DATABASE_ERROR = 'DATABASE_ERROR',
}

export const CallErrorMessages: Record<CallErrorCode, string> = {
  [CallErrorCode.CALL_NOT_FOUND]: 'Emergency call not found',
  [CallErrorCode.CALL_CREATION_FAILED]: 'Failed to create emergency call',
  [CallErrorCode.CALL_UPDATE_FAILED]: 'Failed to update emergency call',
  [CallErrorCode.CALL_DELETE_FAILED]: 'Failed to delete emergency call',
  [CallErrorCode.INVALID_CALL_STATUS]: 'Invalid call status',
  [CallErrorCode.CALL_ALREADY_COMPLETED]: 'Call is already completed',
  [CallErrorCode.CALL_ALREADY_CANCELLED]: 'Call is already cancelled',
  [CallErrorCode.NO_AMBULANCE_ASSIGNED]: 'No ambulance assigned to this call',
  [CallErrorCode.AMBULANCE_DISPATCH_FAILED]: 'Failed to dispatch ambulance',
  [CallErrorCode.HOSPITAL_NOT_SELECTED]: 'No hospital selected for this call',
  [CallErrorCode.HOSPITAL_SELECTION_FAILED]: 'Failed to select hospital',
  [CallErrorCode.INVALID_LOCATION]: 'Invalid location coordinates',
  [CallErrorCode.ROUTE_CALCULATION_FAILED]: 'Failed to calculate route',
  [CallErrorCode.NO_HOSPITALS_FOUND]: 'No hospitals found nearby',
  [CallErrorCode.CONTACT_NOTIFICATION_FAILED]:
    'Failed to notify emergency contacts',
  [CallErrorCode.DRIVER_RESPONSE_FAILED]: 'Failed to process driver response',
  [CallErrorCode.NO_AVAILABLE_DRIVERS]: 'No available drivers found',
  [CallErrorCode.INVALID_USER]: 'Invalid user',
  [CallErrorCode.DATABASE_ERROR]: 'Database operation failed',
};
